#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Redux.TodoMvc.Android.Resource", IsApplication=true)]

namespace Redux.TodoMvc.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020001
			public const int activeRadioButton = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int allRadioButton = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int checkbox = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int clearCompletedButton = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int completedRadioButton = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int editTextId = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int listView1 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int main_footer = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int main_header = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int main_mainsection = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int numberOfTodosRemaining = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int radioGroup = 2130837516;
			
			// aapt resource value: 0x7F020000
			public const int RemoveButton = 2130837504;
			
			// aapt resource value: 0x7F02000D
			public const int selectAllTodosCheckBox = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int todoTextItem = 2130837518;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Footer = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Header = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ListViewItem = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int MainSection = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
